version: '3'
services:
  api:
    build: .
    restart: always
    ports:
      - '1323:1323'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: dcexercise
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dcexercise